version: '3'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - my-network

  wordpress:
    depends_on:
      - db
    image: wordpress:php7.4-fpm-alpine
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    networks:
      - my-network

  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - my-network

volumes:
  db_data:
  wordpress:

networks:
  my-network:

#ceci est un commentaire
